//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeDetaction.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magnitude
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public long Width { get; set; }
        public long Height { get; set; }
        public int ImageId { get; set; }
        public int SobelHId { get; set; }
        public int SobelVId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual SobelH SobelH { get; set; }
        public virtual SobelV SobelV { get; set; }
    }
}
