//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeDetaction.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixDetection
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> BaseId { get; set; }
        public Nullable<int> Parent1 { get; set; }
        public Nullable<int> Parent2 { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public Nullable<decimal> Estimation { get; set; }
        public string Component { get; set; }
        public byte[] Matrix { get; set; }
    }
}
