//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeDetaction.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EdgeDetaction.Core.Repasitorys;

    public partial class EdgeDetectionEntities : DbContext
    {
        public EdgeDetectionEntities()
            : base("name=EdgeDetectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Magnitude> Magnitudes { get; set; }
        public virtual DbSet<SobelH> SobelHs { get; set; }
        public virtual DbSet<SobelV> SobelVs { get; set; }

        public static implicit operator EdgeDetectionEntities(EdgeDetectionDal v)
        {
            throw new NotImplementedException();
        }
    }
}
